import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Briefcase, Wallet, History, TrendingUp, TrendingDown, RefreshCw, 
  Trash2, Play, CheckCircle, AlertTriangle, Coins, X
} from 'lucide-react';

const PaperTrading = () => {
  const [balance, setBalance] = useState(1000000);
  const [trades, setTrades] = useState([]);
  const [activeSignals, setActiveSignals] = useState([]);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  
  // Custom manual order form state
  const [showOrderForm, setShowOrderForm] = useState(false);
  const [symbol, setSymbol] = useState('NIFTY');
  const [type, setType] = useState('CALL');
  const [strike, setStrike] = useState('');
  const [expiry, setExpiry] = useState('');
  const [qty, setQty] = useState(1); // Lots
  const [entryPremium, setEntryPremium] = useState('');
  const [targetPremium, setTargetPremium] = useState('');
  const [stoplossPremium, setStoplossPremium] = useState('');

  const fetchPortfolio = async () => {
    setRefreshing(true);
    try {
      const balanceRes = await axios.get('/api/paper/balance');
      if (balanceRes.data.success) {
        setBalance(balanceRes.data.balance);
      }

      const tradesRes = await axios.get('/api/paper/trades');
      if (tradesRes.data.success) {
        setTrades(tradesRes.data.data);
      }

      // Fetch active OpenClaw signals to offer quick one-click paper trade execution
      const signalsRes = await axios.get('/api/signals?source=OPENCLAW');
      if (signalsRes.data.success) {
        // filter PENDING signals from OpenClaw
        const pending = signalsRes.data.data.filter(s => s.status === 'PENDING');
        setActiveSignals(pending);
      }
    } catch (e) {
      console.error('Failed to fetch paper trading data:', e);
    } finally {
      setRefreshing(false);
    }
  };

  const handleReset = async () => {
    if (!confirm('WARNING: Are you sure you want to reset your virtual account? This will set your balance back to ₹10,00,000 and clear all trades.')) return;
    setLoading(true);
    try {
      const res = await axios.post('/api/paper/reset');
      if (res.data.success) {
        alert('Virtual account reset successfully!');
        fetchPortfolio();
      }
    } catch (e) {
      console.error(e);
      alert('Failed to reset account');
    } finally {
      setLoading(false);
    }
  };

  const handleExitTrade = async (id) => {
    setLoading(true);
    try {
      const res = await axios.post('/api/paper/exit', { id });
      if (res.data.success) {
        alert(`Trade exited successfully! P&L: ₹${res.data.pnl.toFixed(2)}`);
        fetchPortfolio();
      }
    } catch (e) {
      console.error(e);
      alert(e.response?.data?.message || 'Failed to exit trade');
    } finally {
      setLoading(false);
    }
  };

  const handlePlaceOrder = async (e) => {
    e.preventDefault();
    if (!strike || !entryPremium) {
      alert('Strike Price and Entry Premium are required.');
      return;
    }

    setLoading(true);
    try {
      const datePart = expiry ? expiry : '25-Jun'; // fallback placeholder
      const contractName = `${symbol} ${datePart} ${strike} ${type === 'CALL' ? 'CE' : 'PE'}`;
      
      const payload = {
        symbol,
        type,
        contract_name: contractName,
        qty: Number(qty),
        entry_premium: Number(entryPremium),
        entry_spot: 0,
        target_premium: targetPremium ? Number(targetPremium) : null,
        stoploss_premium: stoplossPremium ? Number(stoplossPremium) : null
      };

      const res = await axios.post('/api/paper/trade', payload);
      if (res.data.success) {
        alert('Paper trade executed successfully!');
        setShowOrderForm(false);
        // reset form
        setStrike('');
        setEntryPremium('');
        setTargetPremium('');
        setStoplossPremium('');
        fetchPortfolio();
      }
    } catch (e) {
      console.error(e);
      alert(e.response?.data?.message || 'Order placement failed');
    } finally {
      setLoading(false);
    }
  };

  const executeSignalInPaper = async (signal) => {
    // Check if the signal has contract names generated by OpenClaw
    // Wait, let's find the current premium LTP and contract name from signals
    setLoading(true);
    try {
      // Prompt user for quantity / lots
      const lots = prompt(`Enter number of lots to buy (1 lot size NIFTY=50, BANKNIFTY=15):`, "1");
      if (lots === null || isNaN(lots) || Number(lots) <= 0) {
        setLoading(false);
        return;
      }

      // Extract contract name & premium details from OpenClaw signal metadata
      // Wait, let's see how OpenClaw signal has contract details. We can check if it exists in the database
      // The signal object has: suggestedOptionContract, optionPremiumLtp, optionTarget1, optionStoploss
      // Let's check how the signal fields are stored in the db. We can extract it or use spot values as fallback
      // Wait, let's verify if OpenClaw signals store option premium values
      let contractName = '';
      let entryPremVal = 0;
      let targetPremVal = null;
      let stoplossPremVal = null;

      // Check if it's openclaw signal and has option details
      // Wait, OpenClaw AI outputs suggestedOptionContract, optionPremiumLtp, etc. and saveOpenClawSignalToDb saves it?
      // Wait! Let's check saveOpenClawSignalToDb definition:
      // db.run(`INSERT OR REPLACE INTO ai_signals (symbol, type, entry_price, target_price, stoploss_price, source, status) ...`)
      // Wait, saveOpenClawSignalToDb does NOT save suggestedOptionContract to the DB because database schema only has symbol, type, entry_price, target_price, stoploss_price!
      // Ah! Database table ai_signals only tracks SPOT prices (entry_price is spot, target_price is spot target, stoploss_price is spot SL)!
      // But wait! If the database only has spot prices, we can generate the contract name dynamically!
      // E.g. symbol + " ATM CE", entry_premium is ATR-derived, or we can prompt the user!
      // Or we can query the latest option chain cache to find the ATM strike CE/PE contract name and LTP!
      // Yes! That is extremely smart and dynamic! Let's write an endpoint or function to query it, or do it on-the-fly.
      // Let's check the live option chain cache to get ATM CE/PE details dynamically.
      const cacheKey = `${signal.symbol}_first`;
      const ocRes = await axios.post('/api/openclaw/analyze', { symbol: signal.symbol }); // run a quick analysis to get latest premiums!
      if (ocRes.data.success) {
        const data = ocRes.data.data;
        const indicators = ocRes.data.indicators;
        
        contractName = data.suggestedOptionContract;
        entryPremVal = data.optionPremiumLtp;
        targetPremVal = data.optionTarget1;
        stoplossPremVal = data.optionStoploss;
      }
      
      if (!contractName || !entryPremVal) {
        // Fallback custom prompt if cache/API failed
        alert('Could not resolve Option premium contract automatically. Please use the Manual Order Form.');
        setLoading(false);
        return;
      }

      const payload = {
        symbol: signal.symbol,
        type: signal.type,
        contract_name: contractName,
        qty: Number(lots),
        entry_premium: Number(entryPremVal),
        entry_spot: signal.entry_price,
        target_premium: targetPremVal ? Number(targetPremVal) : null,
        stoploss_premium: stoplossPremVal ? Number(stoplossPremVal) : null
      };

      const res = await axios.post('/api/paper/trade', payload);
      if (res.data.success) {
        alert(`Executed paper trade: Bought ${lots} lot(s) of ${contractName} at ₹${entryPremVal}`);
        fetchPortfolio();
      }
    } catch (err) {
      console.error(err);
      alert('Failed to execute paper trade from signal: ' + (err.response?.data?.message || err.message));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPortfolio();
    
    // Auto-refresh unrealized PnL every 10s to keep it live
    const interval = setInterval(() => {
      fetchPortfolio();
    }, 10000);

    return () => clearInterval(interval);
  }, []);

  const activePositions = trades.filter(t => t.status === 'ACTIVE');
  const pastTrades = trades.filter(t => t.status === 'CLOSED');

  // Calculate portfolio totals
  const totalUnrealizedPnL = activePositions.reduce((sum, t) => sum + (t.pnl || 0), 0);
  const totalRealizedPnL = pastTrades.reduce((sum, t) => sum + (t.pnl || 0), 0);
  const totalPortfolioValue = balance + activePositions.reduce((sum, t) => {
    let lotSize = 50;
    if (t.symbol === 'BANKNIFTY') lotSize = 15;
    else if (t.symbol === 'FINNIFTY') lotSize = 40;
    else if (t.symbol === 'MIDCPNIFTY') lotSize = 75;
    return sum + (t.qty * lotSize * t.entry_premium);
  }, 0) + totalUnrealizedPnL;

  return (
    <div className="container" style={{ padding: '2rem', color: 'white' }}>
      
      {/* Header */}
      <div style={{ marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
            <div className="glow-logo" style={{ background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)', padding: '0.4rem', borderRadius: '8px', boxShadow: '0 0 15px rgba(16, 185, 129, 0.4)' }}>
              <Briefcase size={20} color="white" />
            </div>
            <h1 style={{ fontSize: '1.75rem', margin: 0 }}>Paper Trading Simulator</h1>
          </div>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Virtual Options Portfolio with real-time Dhan Option Chain LTP tracking.</p>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
          <button
            onClick={() => setShowOrderForm(!showOrderForm)}
            style={{
              background: 'rgba(255,255,255,0.05)',
              color: 'white',
              border: '1px solid var(--border-color)',
              padding: '0.5rem 1rem',
              borderRadius: '8px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem'
            }}
          >
            <Play size={14} fill="white" /> Custom Manual Order
          </button>
          
          <button
            onClick={fetchPortfolio}
            disabled={refreshing}
            style={{
              background: 'rgba(255,255,255,0.05)',
              color: 'white',
              border: '1px solid var(--border-color)',
              padding: '0.5rem 1rem',
              borderRadius: '8px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem'
            }}
          >
            <RefreshCw size={14} className={refreshing ? 'spin' : ''} /> Refresh
          </button>

          <button
            onClick={handleReset}
            disabled={loading}
            style={{
              background: 'rgba(239, 68, 68, 0.1)',
              color: '#ef4444',
              border: '1px solid rgba(239, 68, 68, 0.2)',
              padding: '0.5rem 1rem',
              borderRadius: '8px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem'
            }}
          >
            <Trash2 size={14} /> Reset Wallet
          </button>
        </div>
      </div>

      {/* Portfolio Stats Widgets */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1.5rem', marginBottom: '2rem' }}>
        
        <div className="glass-panel" style={{ padding: '1.25rem', borderLeft: '4px solid var(--accent-primary)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '0.5rem' }}>
            <span>Available Balance</span>
            <Wallet size={16} />
          </div>
          <div style={{ fontSize: '1.5rem', fontWeight: '800' }}>₹{balance.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
        </div>

        <div className="glass-panel" style={{ padding: '1.25rem', borderLeft: '4px solid #10b981' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '0.5rem' }}>
            <span>Portfolio Value (Margin+PnL)</span>
            <Coins size={16} />
          </div>
          <div style={{ fontSize: '1.5rem', fontWeight: '800', color: '#10b981' }}>₹{totalPortfolioValue.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
        </div>

        <div className="glass-panel" style={{ padding: '1.25rem', borderLeft: `4px solid ${totalUnrealizedPnL >= 0 ? 'var(--bullish)' : 'var(--bearish)'}` }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '0.5rem' }}>
            <span>Unrealized P&L (Active)</span>
            {totalUnrealizedPnL >= 0 ? <TrendingUp size={16} color="var(--bullish)" /> : <TrendingDown size={16} color="var(--bearish)" />}
          </div>
          <div style={{ fontSize: '1.5rem', fontWeight: '800', color: totalUnrealizedPnL >= 0 ? 'var(--bullish)' : 'var(--bearish)' }}>
            {totalUnrealizedPnL >= 0 ? '+' : ''}₹{totalUnrealizedPnL.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </div>
        </div>

        <div className="glass-panel" style={{ padding: '1.25rem', borderLeft: `4px solid ${totalRealizedPnL >= 0 ? 'var(--bullish)' : 'var(--bearish)'}` }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '0.5rem' }}>
            <span>Realized P&L (Closed)</span>
            {totalRealizedPnL >= 0 ? <TrendingUp size={16} color="var(--bullish)" /> : <TrendingDown size={16} color="var(--bearish)" />}
          </div>
          <div style={{ fontSize: '1.5rem', fontWeight: '800', color: totalRealizedPnL >= 0 ? 'var(--bullish)' : 'var(--bearish)' }}>
            {totalRealizedPnL >= 0 ? '+' : ''}₹{totalRealizedPnL.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </div>
        </div>

      </div>

      {/* Manual Order Form Overlay Panel */}
      {showOrderForm && (
        <div className="glass-panel" style={{ padding: '1.5rem', marginBottom: '2rem', border: '1px solid var(--accent-primary)', position: 'relative' }}>
          <button 
            onClick={() => setShowOrderForm(false)}
            style={{ position: 'absolute', top: '1rem', right: '1rem', background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}
          >
            <X size={20} />
          </button>
          
          <h3 style={{ margin: '0 0 1.25rem 0', fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Coins size={18} color="var(--accent-primary)" /> Place Custom Virtual Order
          </h3>
          
          <form onSubmit={handlePlaceOrder} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
            <div>
              <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Symbol</label>
              <select value={symbol} onChange={(e) => setSymbol(e.target.value)} style={{ width: '100%', background: '#1c2128', border: '1px solid var(--border-color)', color: 'white', padding: '0.5rem', borderRadius: '6px' }}>
                <option value="NIFTY">NIFTY</option>
                <option value="BANKNIFTY">BANKNIFTY</option>
                <option value="FINNIFTY">FINNIFTY</option>
                <option value="MIDCPNIFTY">MIDCPNIFTY</option>
              </select>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Option Type</label>
              <select value={type} onChange={(e) => setType(e.target.value)} style={{ width: '100%', background: '#1c2128', border: '1px solid var(--border-color)', color: 'white', padding: '0.5rem', borderRadius: '6px' }}>
                <option value="CALL">CALL (CE)</option>
                <option value="PUT">PUT (PE)</option>
              </select>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Strike Price</label>
              <input type="number" placeholder="e.g. 22000" value={strike} onChange={(e) => setStrike(e.target.value)} required style={{ width: '100%', background: '#1c2128', border: '1px solid var(--border-color)', color: 'white', padding: '0.5rem', borderRadius: '6px' }} />
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Expiry Date (Format: 'DD-MMM')</label>
              <input type="text" placeholder="e.g. 25-Jun" value={expiry} onChange={(e) => setExpiry(e.target.value)} style={{ width: '100%', background: '#1c2128', border: '1px solid var(--border-color)', color: 'white', padding: '0.5rem', borderRadius: '6px' }} />
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Quantity (Lots)</label>
              <input type="number" min="1" value={qty} onChange={(e) => setQty(e.target.value)} required style={{ width: '100%', background: '#1c2128', border: '1px solid var(--border-color)', color: 'white', padding: '0.5rem', borderRadius: '6px' }} />
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Entry Premium (₹)</label>
              <input type="number" step="0.05" placeholder="e.g. 120.50" value={entryPremium} onChange={(e) => setEntryPremium(e.target.value)} required style={{ width: '100%', background: '#1c2128', border: '1px solid var(--border-color)', color: 'white', padding: '0.5rem', borderRadius: '6px' }} />
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Target Premium (Optional)</label>
              <input type="number" step="0.05" placeholder="e.g. 150.00" value={targetPremium} onChange={(e) => setTargetPremium(e.target.value)} style={{ width: '100%', background: '#1c2128', border: '1px solid var(--border-color)', color: 'white', padding: '0.5rem', borderRadius: '6px' }} />
            </div>

            <div>
              <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Stoploss Premium (Optional)</label>
              <input type="number" step="0.05" placeholder="e.g. 95.00" value={stoplossPremium} onChange={(e) => setStoplossPremium(e.target.value)} style={{ width: '100%', background: '#1c2128', border: '1px solid var(--border-color)', color: 'white', padding: '0.5rem', borderRadius: '6px' }} />
            </div>

            <div style={{ gridColumn: '1 / -1', display: 'flex', justifyContent: 'flex-end', marginTop: '0.5rem' }}>
              <button 
                type="submit" 
                disabled={loading}
                style={{
                  background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                  color: 'white',
                  border: 'none',
                  padding: '0.55rem 1.5rem',
                  borderRadius: '6px',
                  fontWeight: '700',
                  cursor: loading ? 'not-allowed' : 'pointer'
                }}
              >
                Execute Buy Order
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Active Signal Board (Quick Execution) */}
      {activeSignals.length > 0 && (
        <div className="glass-panel" style={{ padding: '1.25rem', marginBottom: '1.5rem', border: '1px solid rgba(16, 185, 129, 0.2)' }}>
          <h3 style={{ margin: '0 0 1rem 0', fontSize: '0.95rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: '#10b981' }}>
            <Play size={16} fill="#10b981" /> Active OpenClaw Trade Alerts (One-Click Paper Execution)
          </h3>
          <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
            {activeSignals.map((sig) => (
              <div 
                key={sig.id} 
                style={{ 
                  background: 'rgba(255,255,255,0.02)', 
                  border: '1px solid var(--border-color)', 
                  padding: '0.75rem 1rem', 
                  borderRadius: '8px',
                  display: 'flex', 
                  alignItems: 'center', 
                  justifyContent: 'space-between',
                  gap: '2rem',
                  minWidth: '280px',
                  flex: '1'
                }}
              >
                <div>
                  <div style={{ fontWeight: '700', fontSize: '0.95rem' }}>{sig.symbol} {sig.type}</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Spot Entry: ₹{sig.entry_price.toFixed(2)} | Target: ₹{sig.target_price.toFixed(2)}</div>
                </div>
                <button
                  onClick={() => executeSignalInPaper(sig)}
                  disabled={loading}
                  style={{
                    background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
                    color: 'white',
                    border: 'none',
                    padding: '0.4rem 1rem',
                    borderRadius: '6px',
                    fontSize: '0.8rem',
                    fontWeight: '700',
                    cursor: 'pointer'
                  }}
                >
                  Paper Trade
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Grid: Active Positions & History */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '2rem' }}>
        
        {/* Active Positions */}
        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <h3 style={{ margin: '0 0 1.25rem 0', fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Briefcase size={18} color="var(--accent-primary)" /> Active Paper Positions ({activePositions.length})
          </h3>

          {activePositions.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '3rem 0', color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
              <AlertTriangle size={32} style={{ marginBottom: '0.5rem', color: 'var(--text-muted)' }} />
              <div>No active paper positions. Go to OpenClaw AI to trigger a trade signal or place a custom order!</div>
            </div>
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.9rem' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.05)', textAlign: 'left', color: 'var(--text-secondary)' }}>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Contract</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Lots</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Entry Premium</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Target</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Stoploss</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Unrealized P&L</th>
                    <th style={{ padding: '0.75rem 0.5rem', textAlign: 'right' }}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {activePositions.map((pos) => {
                    const isBullish = pos.pnl >= 0;
                    return (
                      <tr key={pos.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.03)' }}>
                        <td style={{ padding: '1rem 0.5rem', fontWeight: 'bold' }}>{pos.contract_name}</td>
                        <td style={{ padding: '1rem 0.5rem' }}>{pos.qty}</td>
                        <td style={{ padding: '1rem 0.5rem' }}>₹{pos.entry_premium.toFixed(2)}</td>
                        <td style={{ padding: '1rem 0.5rem', color: 'var(--bullish)' }}>{pos.target_premium ? `₹${pos.target_premium.toFixed(2)}` : 'N/A'}</td>
                        <td style={{ padding: '1rem 0.5rem', color: 'var(--bearish)' }}>{pos.stoploss_premium ? `₹${pos.stoploss_premium.toFixed(2)}` : 'N/A'}</td>
                        <td style={{ padding: '1rem 0.5rem', color: isBullish ? 'var(--bullish)' : 'var(--bearish)', fontWeight: 'bold' }}>
                          {isBullish ? '+' : ''}₹{pos.pnl.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                        </td>
                        <td style={{ padding: '1rem 0.5rem', textAlign: 'right' }}>
                          <button
                            onClick={() => handleExitTrade(pos.id)}
                            disabled={loading}
                            style={{
                              background: 'rgba(239, 68, 68, 0.1)',
                              color: '#ef4444',
                              border: '1px solid rgba(239, 68, 68, 0.2)',
                              padding: '0.35rem 0.75rem',
                              borderRadius: '6px',
                              cursor: 'pointer',
                              fontWeight: '600',
                              fontSize: '0.8rem'
                            }}
                          >
                            Exit
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Paper Trade History */}
        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <h3 style={{ margin: '0 0 1.25rem 0', fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <History size={18} color="var(--text-secondary)" /> Trade History ({pastTrades.length})
          </h3>

          {pastTrades.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '2rem 0', color: 'var(--text-secondary)', fontSize: '0.85rem' }}>
              No completed trades yet.
            </div>
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.05)', textAlign: 'left', color: 'var(--text-secondary)' }}>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Date</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Contract</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Lots</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Entry Premium</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Exit Premium</th>
                    <th style={{ padding: '0.75rem 0.5rem' }}>Final P&L</th>
                    <th style={{ padding: '0.75rem 0.5rem', textAlign: 'right' }}>Outcome</th>
                  </tr>
                </thead>
                <tbody>
                  {pastTrades.map((trade) => {
                    const isWin = trade.pnl >= 0;
                    return (
                      <tr key={trade.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.03)', opacity: 0.85 }}>
                        <td style={{ padding: '0.85rem 0.5rem', color: 'var(--text-muted)' }}>
                          {new Date(trade.created_at).toLocaleDateString('en-IN')}
                        </td>
                        <td style={{ padding: '0.85rem 0.5rem', fontWeight: '600' }}>{trade.contract_name}</td>
                        <td style={{ padding: '0.85rem 0.5rem' }}>{trade.qty}</td>
                        <td style={{ padding: '0.85rem 0.5rem' }}>₹{trade.entry_premium.toFixed(2)}</td>
                        <td style={{ padding: '0.85rem 0.5rem' }}>₹{trade.exit_premium ? trade.exit_premium.toFixed(2) : '0.00'}</td>
                        <td style={{ padding: '0.85rem 0.5rem', color: isWin ? 'var(--bullish)' : 'var(--bearish)', fontWeight: 'bold' }}>
                          {isWin ? '+' : ''}₹{trade.pnl.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                        </td>
                        <td style={{ padding: '0.85rem 0.5rem', textAlign: 'right' }}>
                          <span style={{
                            background: isWin ? 'rgba(0, 200, 5, 0.1)' : 'rgba(239, 68, 68, 0.1)',
                            color: isWin ? 'var(--bullish)' : 'var(--bearish)',
                            padding: '0.2rem 0.5rem',
                            borderRadius: '4px',
                            fontWeight: 'bold',
                            fontSize: '0.75rem'
                          }}>
                            {isWin ? 'PROFIT' : 'LOSS'}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>

      </div>

    </div>
  );
};

export default PaperTrading;
